#!/usr/bin/perl

use strict;
use warnings;

# split_vigenere.pl  Split Vigenere cipher text into separate files
# Author: Niall Durham, niall.durham@gmail.com
# Last modified: 09 June 2005

use Getopt::Std;

my $MAPFILE = 'vmap.txt';

our %opts;
getopts('fo:', \%opts);                 # force, output prefix

my $out_prefix = ($opts{o}) ? ($opts{o}) : 'split';
usage($0) if ($#ARGV <= 0); 
my $num = shift(@ARGV);

# Read in vigenere message.
my $file = shift(@ARGV);
my $msg;
open my $fh, '<', $file || die "Unable to open $file for reading: $!";
{
    local $/;
    $msg = <$fh>;
}
close($fh);
$msg = uc($msg);
$msg =~ s/\s+//g;

# Split message into pieces.
my %vsplit;
my $len = length($msg);
foreach my $i (0..$len-1) {
    my $c = substr($msg, $i, 1);           # next char
    my $idx = $i % $num;
    my $key = "$out_prefix$idx";
    $vsplit{$key} .= $c;
}

# Write out each portion of the message as a separate file.
foreach my $k (sort keys %vsplit) {
    my $len = length($vsplit{$k});
    my $fn = "$k.txt";                  # filename
    open my $fh, '>', $fn || die "Unable to open $fn for writing: $!";
    print $fh "$vsplit{$k}\n";
    close($fh);
    print "Wrote $len to $fn.\n";
}

# Output template map file
if (-e $MAPFILE and not $opts{f}) {
    warn "?use -f option to overwrite existing mapfile $MAPFILE\n";
}
else {
    open my $fh, '>', $MAPFILE or die "Unable to open $MAPFILE for writing: $!";
    print $fh "# $MAPFILE [intially] automatically generated by $0\n";
    for my $k (sort keys %vsplit) {
        print $fh "? : $k.txt\n";
    }
    close $fh;
}

exit 0;


# usage information
sub usage
{
    my ($arg0) = @_;

    print "$arg0: <num_splits> <input_file>\n";
    exit 0;
}

